revert to crystal-0.18.7 due to compilation error
in ./src/dstat-redis/program.cr:9: undefined method 'map' for Try(Hash(String, Float64 | Int32 | Int64 | String)) (compile-time type is Try(Hash(String, Float64 | Int32 | Int64 | String))+) (did you mean 'tap'?)

      result = tval.map{|val| @output.output(val)}